<?php

class Vavilen84_PostAccountCreate_Block_Data extends Mage_Core_Block_Template
{
    public function __construct(array $args = array())
    {
        parent::__construct($args);

        $orderId = Mage::getSingleton('checkout/session')->getLastOrderId();
        if ($orderId) {
            $order = Mage::getModel('sales/order')->load($orderId);
            if (!empty($order)) {
                $this->registerUser($order);
            }
        }
    }

    protected function registerUser($order)
    {
        $websiteId = Mage::getModel('core/store')->load($order->getStoreId())->getWebsiteId();
        $store = Mage::getModel('core/store')->load($order->getStoreId());

        $billingAddress = []; // Some billing address will be here.
        //Check whether the customer already registered or not
        $customer = Mage::getModel('customer/customer')
            ->setWebsiteId($websiteId)
            ->loadByEmail($order->getCustomerEmail());
        if (!$customer->getId()) {
            //Create the new customer account if not registered
            $customer = Mage::getModel('customer/customer');
            $customer->setWebsiteId($order->getStoreId())
                ->setStore($store)
                ->setFirstname($order->getCustomerFirstname())
                ->setLastname($order->getCustomerLastname())
                ->setEmail($order->getCustomerEmail());
            try {
                $password = $customer->generatePassword();
                $customer->setPassword($password);
                //Set the customer as confirmed
                $customer->setForceConfirmed(true); // TODO: need to check with current merchant.
                $customer->save();
                $customer->setConfirmation(null);
                $customer->save();
                //Set customer address
                $customerId = $customer->getId();
                $customAddress = Mage::getModel('customer/address');
                $customAddress->setData($billingAddress)
                    ->setCustomerId($customerId)
                    ->setIsDefaultBilling('1')
                    ->setIsDefaultShipping('1')
                    ->setSaveInAddressBook('1');
                //Save customer address
                $customAddress->save();
                //Send new account email to customer
                $storeId = $customer->getSendemailStoreId();
                $customer->sendNewAccountEmail('registered', '', $storeId);
                //Set password remainder email if the password is auto generated by magento
                $customer->sendPasswordReminderEmail();

                // login customer
                $session = Mage::getSingleton('customer/session');
                $session
                    ->loginById($customerId)
                    ->setCustomerAsLoggedIn($customer);

            } catch (Exception $e) {
                Mage::logException($e);
            }
        }
    }
}